version: "3.9"

services:
  redis:
    image: 'redis'
    expose:
     - "6379"
    
  gateway:
    depends_on:
      - ms-articles
    build:
      dockerfile: ../micro.Dockerfile
      context: ./gateway
      args:
        - SUBFOLDER=gateway
    working_dir: /project/gateway
    environment:
      - NODE_ENV=development
    expose:
      - "3000"
    ports:
      - 3000:3000
    secrets:
      - source: user_ssh_key
        target: /root/.ssh/id_rsa
        mode: 0600

  ms-articles:
    build:
      dockerfile: ../micro.Dockerfile
      context: ./ms-articles
      args:
        - SUBFOLDER=ms-articles
    working_dir: /project/ms-articles
    environment:
      - NODE_ENV=development
    expose:
      - "8881"
    ports:
      - 8881:8881
    secrets:
      - source: user_ssh_key
        target: /root/.ssh/id_rsa
        mode: 0600
  
  fetcher:
    build:
      dockerfile: Dockerfile
      context: ./fetcher
    working_dir: /app
    environment:
      - NODE_ENV=development
    expose:
      - "5000"
    ports:
      - 5000:5000
    secrets:
      - user_ssh_key



secrets:
  user_ssh_key:
    file: c:\users\andre\.ssh\id_rsa
