version: "3.9"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: melipassword
      MYSQL_DATABASE: meli
    expose:
      - 3306

  redis:
    image: 'redis'
    expose:
     - 6379
  
  bullboard:
    depends_on:
      - redis
    container_name: bullboard
    image: deadly0/bull-board
    ports:
      - 3030:3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BULL_VERSION=BULL
    
  gateway:
    depends_on:
      - ms-articles
    build:
      dockerfile: ../micro.Dockerfile
      context: ./gateway
      args:
        - SUBFOLDER=gateway
    working_dir: /project/gateway
    environment:
      - NODE_ENV=development
    expose:
      - "3000"
    ports:
      - 3000:3000
    secrets:
      - source: user_ssh_key
        target: /root/.ssh/id_rsa
        mode: 0600

  ms-articles:
    depends_on:
      - fetcher
      - db
      - redis
    build:
      dockerfile: ../micro.Dockerfile
      context: ./ms-articles
      args:
        - SUBFOLDER=ms-articles
    working_dir: /project/ms-articles
    environment:
      - NODE_ENV=development
    expose:
      - "8881"
    ports:
      - 8881:8881
    secrets:
      - source: user_ssh_key
        target: /root/.ssh/id_rsa
        mode: 0600
  
  fetcher:
    depends_on:
      - redis
    build:
      dockerfile: ../micro.Dockerfile
      context: ./fetcher
      args:
        - SUBFOLDER=fetcher
    working_dir: /project/fetcher
    environment:
      - NODE_ENV=development
    expose:
      - "8891"
    ports:
      - 8891:8891
    secrets:
      - source: user_ssh_key
        target: /root/.ssh/id_rsa
        mode: 0600

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    depends_on:
      - db
    ports:
      - 3080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=melipassword
  
  frontend:
    depends_on:
      - ms-articles
    build:
      dockerfile: ../micro.Dockerfile
      context: ./frontend
      args:
        - SUBFOLDER=frontend
    working_dir: /project/frontend
    environment:
      - NODE_ENV=development
    expose:
      - "3000"
    ports:
      - 3040:3000
    secrets:
      - source: user_ssh_key
        target: /root/.ssh/id_rsa
        mode: 0600
    command: npm run start


secrets:
  user_ssh_key:
    file: c:\users\andre\.ssh\id_rsa
